void Bar(){

         typewrite("\nBlaze: oh shit. They were all skittles colors I didn't even realize it. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: yeah. Well you know what they can taste the rainboe in jail. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: wh- what do you mean? Like different colored dicks? ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<"You both laugh* "<<endl;
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: shit. Sorry. Sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou:  I actually didn't know what i meant, ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n But you know it should've been that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I'm a little buzzed. I don't really make jokes like that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  I think Visi's rubbing off on me. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: uhh someone I work with, it's, yeah. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<"Sees blazer chugs her alcohol drink*"<<endl;
         cout<<" "<<endl;
         char a;
         cout<<"W = that feels like a challange "<<endl;
         cout<<"A = Rough day? "<<endl;
         cout<<"D = Impressive. "<<endl;
         cin>>a;
         if(a == 'a' ||a == 'A'){
          typewrite("\nYou: I can't tell which one of us had the rough day");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: oh. No. I had a great day. Well, that's not totally true. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Oh, you're joking. Sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's fine. Don't worry about keeping up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  Something to do with the powers. . . It,  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  It takes a lot for me to feel anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: what a sad sentence.  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Hey, you should give yourself more credit. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n To do what you did, for as long as you did. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Especially without superpowers. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Not true. Whatddaya call this? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Breaks finger and puts it back like nothing happened*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I can fix that one for you too");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: No thanks. I like this one. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So how'd you afford all that? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must've spent hundreds of thousands - - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you'll understand when the check comes. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: you're serious. Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Yeah, I basically burned though my entire inheritance keeping it going. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Last couple years have just been duct and sheer determination. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Wh- why did you do it? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Do what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Sacrifice everything to be a superhero to the point of financial");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: ruin? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I was gonna say hardship, but ruin was the first word that came to mind, yeah.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must be completely broke at this point. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else if (a == 'd'|| a == 'D'){
         typewrite("\nYou: That was. . . Impressive. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's fine. Don't worry about keeping up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  Something to do with the powers. . . It,  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  It takes a lot for me to feel anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: what a sad sentence.  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Hey, you should give yourself more credit. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n To do what you did, for as long as you did. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Especially without superpowers. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Not true. Whatddaya call this? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Breaks finger and puts it back like nothing happened*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I can fix that one for you too");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: No thanks. I like this one. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So how'd you afford all that? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must've spent hundreds of thousands - - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you'll understand when the check comes. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: you're serious. Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Yeah, I basically burned though my entire inheritance keeping it going. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Last couple years have just been duct and sheer determination. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Wh- why did you do it? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Do what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Sacrifice everything to be a superhero to the point of financial");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: ruin? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I was gonna say hardship, but ruin was the first word that came to mind, yeah.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must be completely broke at this point. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else if (a == 'w' || a == 'w'){
          typewrite("\n You: that, feels like a challenge");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: oh. No. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's fine. Don't worry about keeping up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  Something to do with the powers. . . It,  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  It takes a lot for me to feel anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: what a sad sentence.  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Hey, you should give yourself more credit. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n To do what you did, for as long as you did. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Especially without superpowers. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Not true. Whatddaya call this? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Breaks finger and puts it back like nothing happened*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I can fix that one for you too");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: No thanks. I like this one. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So how'd you afford all that? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must've spent hundreds of thousands - - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you'll understand when the check comes. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: you're serious. Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Yeah, I basically burned though my entire inheritance keeping it going. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Last couple years have just been duct and sheer determination. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Wh- why did you do it? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Do what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Sacrifice everything to be a superhero to the point of financial");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: ruin? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I was gonna say hardship, but ruin was the first word that came to mind, yeah.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must be completely broke at this point. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else{
          typewrite("\n You: that, feels like a challenge");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: oh. No. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's fine. Don't worry about keeping up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  Something to do with the powers. . . It,  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n  It takes a lot for me to feel anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: what a sad sentence.  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Hey, you should give yourself more credit. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n To do what you did, for as long as you did. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Especially without superpowers. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Not true. Whatddaya call this? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Breaks finger and puts it back like nothing happened*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I can fix that one for you too");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: No thanks. I like this one. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So how'd you afford all that? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must've spent hundreds of thousands - - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you'll understand when the check comes. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: you're serious. Millions. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Yeah, I basically burned though my entire inheritance keeping it going. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Last couple years have just been duct and sheer determination. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Wh- why did you do it? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Do what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Sacrifice everything to be a superhero to the point of financial");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: ruin? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: I was gonna say hardship, but ruin was the first word that came to mind, yeah.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You must be completely broke at this point. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         cout<<"=====Choice====="<<endl;
         char s;
         cout<<"W = I don't know. . . "<<endl;
         cout<<"A = I like helping people. "<<endl;
         cout<<"D = only thing I'm good at. "<<endl;
         cin>>s;

         if(s == 'd'|| s == 'D'){
          typewrite("\nYou: honestly, it's the only thing I'm good at. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n! Blonde blazer will remember that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Now, that's a sad sentence. Come on, that can't be true. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I guess it could be true.");
         this_thread::sleep_for(chrono::seconds(2));
         blonde_blazerInterest += 1;
         }
         else if (s == 'a'|| s =='A'){
          typewrite("\n I don't know, I guess i just like helping people. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n! Blonde Blazer will remember that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So are you drunk yet, or what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Eh, yeah, I should probably be switching to water. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Good, cause I was hoping after some drinks to loosen you up, ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I could learn a little more about you and uh. . .  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n If it that went well. . . Present you with a proposition. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You: a proposition");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Yeah, I'm just trying to figure out if this is a fit or not. You know?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Then it's just a matter of picking the right moment. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         blonde_blazerInterest += 2;
         }
         else if(s == 'D'|| s == 'd'){
          typewrite("\nYou: honestly, it's the only thing I'm good at. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n ! Blonde blazer will remember that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Now, that's a sad sentence. Come on, that can't be true. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I guess it could be true.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So are you drunk yet, or what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Eh, yeah, I should probably be switching to water. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Good, cause I was hoping after some drinks to loosen you up, ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I could learn a little more about you and uh. . .  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n If it that went well. . . Present you with a proposition. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You: a proposition");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Yeah, I'm just trying to figure out if this is a fit or not. You know?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Then it's just a matter of picking the right moment. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         blonde_blazerInterest += 1;
         }
         else{
          typewrite("\nYou: honestly, it's the only thing I'm good at. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n ! Blonde blazer will remember that. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Now, that's a sad sentence. Come on, that can't be true. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I guess it could be true.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: So are you drunk yet, or what? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Eh, yeah, I should probably be switching to water. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Good, cause I was hoping after some drinks to loosen you up, ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I could learn a little more about you and uh. . .  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n If it that went well. . . Present you with a proposition. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You: a proposition");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Yeah, I'm just trying to figure out if this is a fit or not. You know?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Then it's just a matter of picking the right moment. ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         blonde_blazerInterest += 1;
         }
         char d;
         cout<<"=====CHOICE====="<<endl;
         cout<<"W = Hopefully nothing scandalous. "<<endl;
         cout<<"A = Sounds intriguing. "<<endl;
         cout<<"D = A bar proposition? "<<endl;
         cin>>d;
         if(d == 'w' || d == 'W'){
          typewrite("\nYou: Okay. . . Hopefully it's nothing too. Scandalous. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nDrinks*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: that's actually- - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Not water.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: This is like pure alcohol*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's not like alcohol, it is alcohol. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I know because you spit it directly into my open mouth");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: you drink hard liquor straight from a pint glass? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: actually, I usually just drink it straight from the bottle but. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I thought that would be embarrassing. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I'm gonna go clean up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: I'm so sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : hey bitch.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Hey! I'm talking to you bitch! ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Alright just so you know, I only turned around cause someone yelled, not because I'm a ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n bitch or anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : don't you watch the news? This is a superhero bar. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Oh, wow, are you a superhero? That's so cool. Is this your power?  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're like, tell people obvious shit guy? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : you're really gonna act like you don't remember me? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait it's coming back to me. . . Hold on, yeah, it's coming back to me. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Oh, wait, wait, oh I know it. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else if(d == 'a'|| d =='A'){
          typewrite("\nYou: Well, I have to say Blazer, that does sound intriguing. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nDrinks*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: that's actually- - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nSpits the drink on blazer*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Not water.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: This is like pure alcohol*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's not like alcohol, it is alcohol. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I know because you spit it directly into my open mouth");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: you drink hard liquor straight from a pint glass? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: actually, I usually just drink it straight from the bottle but. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I thought that would be embarrassing. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I'm gonna go clean up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: I'm so sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : hey bitch.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Hey! I'm talking to you bitch! ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Alright just so you know, I only turned around cause someone yelled, not because I'm a ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n bitch or anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : don't you watch the news? This is a superhero bar. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Oh, wow, are you a superhero? That's so cool. Is this your power?  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're like, tell people obvious shit guy? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : you're really gonna act like you don't remember me? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait it's coming back to me. . . Hold on, yeah, it's coming back to me. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Oh, wait, wait, oh I know it. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else if(d == 'd'|| d == 'D'){
          typewrite("\nYou: well, a propositions late at night in a bar can go any number of ways.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nDrinks*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: that's actually- - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nSpits the drink on blazer*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Not water.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: This is like pure alcohol*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's not like alcohol, it is alcohol. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I know because you spit it directly into my open mouth");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: you drink hard liquor straight from a pint glass? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: actually, I usually just drink it straight from the bottle but. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I thought that would be embarrassing. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I'm gonna go clean up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: I'm so sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : hey bitch.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Hey! I'm talking to you bitch! ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Alright just so you know, I only turned around cause someone yelled, not because I'm a ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n bitch or anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : don't you watch the news? This is a superhero bar. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Oh, wow, are you a superhero? That's so cool. Is this your power?  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're like, tell people obvious shit guy? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : you're really gonna act like you don't remember me? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait it's coming back to me. . . Hold on, yeah, it's coming back to me. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Oh, wait, wait, oh I know it. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         else{
         typewrite("\nYou: well, a propositions late at night in a bar can go any number of ways.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nDrinks*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: that's actually- - ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nSpits the drink on blazer*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: Not water.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: This is like pure alcohol*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: It's not like alcohol, it is alcohol. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I know because you spit it directly into my open mouth");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: you drink hard liquor straight from a pint glass? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nBlazer: actually, I usually just drink it straight from the bottle but. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I thought that would be embarrassing. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n I'm gonna go clean up. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: I'm so sorry. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : hey bitch.. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Hey! I'm talking to you bitch! ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Alright just so you know, I only turned around cause someone yelled, not because I'm a ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n bitch or anything. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : don't you watch the news? This is a superhero bar. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: Oh, wow, are you a superhero? That's so cool. Is this your power?  ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're like, tell people obvious shit guy? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n??? : you're really gonna act like you don't remember me? ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait it's coming back to me. . . Hold on, yeah, it's coming back to me. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Oh, wait, wait, oh I know it. . . ");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
         cout<<"=====Choice====="<<endl;
         char w;
         cout<<"W = Dr. Don't do shit"<<endl;
         cout<<"A = Mr. Wet Ponytail"<<endl;
         cout<<"D = Sunglasses at Night guy"<<endl;
         cin>>w;

         if(w == 'D'|| w =='d'){
          typewrite("\nYou : You are sunglasses, Indoors, at Night guy. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Your superpower is that you're able to let everyone know in the room that you're a douchebag");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Cause you should literally never do that unless you're at the final table of the world Series of ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n poker - - - but even then, if you win, you're still a fucking loser. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: No, Mecha Bitch, I control the fire- - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: the fire?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: AND the flame. . . and my skin does not burn. . .");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: I am Flambae, and you - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait, oh shit I do remember you.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're that shitty villain I busted up.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: Not anymore, Mecha Dick.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n As I literally just said, I am flambae, a real superhero.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n And you are not Mechaman anymore");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you need to get the fuck out of here.");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
         }
        else if(w == 'a'|| w == 'A'){
          typewrite("\nYou: you know what, you are Mr. Wet Ponytail. ");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYour superpower is in, obviously, your pony tail, which, aside from being disgust");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n kills themself.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: No, Mecha Bitch, I control the fire- - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: the fire?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: AND the flame. . . and my skin does not burn. . .");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: I am Flambae, and you - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait, oh shit I do remember you.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're that shitty villain I busted up.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: Not anymore, Mecha Dick.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n As I literally just said, I am flambae, a real superhero.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n And you are not Mechaman anymore");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you need to get the fuck out of here.");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
        }
        else if(w == 'W'|| w == 'w'){
          typewrite("\n You are Dr. Don't Do shit.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Your deal is you walk up to people, look threatening, talk a big game then don’t do shit about it.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n Also, you're not a real doctor cause you're a fuckin idiot.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: No, Mecha Bitch, I control the fire- - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: the fire?");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n???: AND the flame. . . and my skin does not burn. . .");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: I am Flambae, and you - -");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: wait, oh shit I do remember you.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n You're that shitty villain I busted up.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: Not anymore, Mecha Dick.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n As I literally just said, I am flambae, a real superhero.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n And you are not Mechaman anymore");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\n So you need to get the fuck out of here.");
         this_thread::sleep_for(chrono::seconds(2));
         cout<<" "<<endl;
        }
        cout<<"Note: Choose which bottle to throw him with."<<endl;
        char q;
        cout<<"=====CHOICE====="<<endl;
        cout<<"A = [WATER}"<<endl;
        cout<<"D ={ALCOHOL}"<<endl;
        cin>>q;
        if(q == 'a' || q == 'Q'){
          cout<<"Throws him water*"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
         cout<<"! Everyone will remember that"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nYou: there easy way");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae: I've been waiting a long time for this.");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nFlambae throws a punch*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nSlips through the water you threw him with*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nHits his teeth in the counter and loses some of it*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nGets knocked out*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nShe comforts you and brings you somewhere else*");
        }
        else if(q == 'd' || q == 'D'){
         cout<<"Throws him pure alcohol*"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
         cout<<"! Everyone will remember that"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
          typewrite("\nFire spreads throughout his body*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nHe panics and runs*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nStore kicks you out*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nShe comforts you and brings you somewhere else*");
         Flambae_Anger_Level += 3;
        }
        else{
          cout<<"Throws him pure alcohol*"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
         cout<<"! Everyone will remember that"<<endl;
         this_thread::sleep_for(chrono::seconds(2));
          typewrite("\nFire spreads throughout his body*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nHe panics and runs*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nStore kicks you out*");
         this_thread::sleep_for(chrono::seconds(2));
         typewrite("\nShe comforts you and brings you somewhere else*");
         Flambae_Anger_Level += 5;
         blonde_blazerInterest += 3;
        
        }
