

#include <iostream>
#include <unistd.h>// function for typewrite 
#include <string>
#include <thread>//function for pause
#include <chrono>// declaration of seconds and milliseconds
using namespace std;
void typewrite(string text, int speed = 50000){
    for ( char c : text){
        cout << c << flush;
        
        usleep(speed);
    }
}

void warehouse(){
        typewrite("\nSuiting upp. . .");
        this_thread::sleep_for(chrono::seconds(3));
        std::cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                 std::cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                std:: cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
              std::   cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
               typewrite("\nEntering mech. . .");
        this_thread::sleep_for(chrono::seconds(2));
                std:: cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
              typewrite("\nInvading warehouse . . ");
        this_thread::sleep_for(chrono::seconds(2));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
             std::    cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
              std::   cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
              std::   cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                typewrite("\nBeat up some hooligans*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEntering Boss room. . .");
        this_thread::sleep_for(chrono::seconds(3));
               std::  cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
               std::  cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
               std::  cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
               std::  cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                typewrite("\nSees cctv footages*");
        this_thread::sleep_for(chrono::seconds(2));
        cout<<" "<<endl;
        char a, w, c;
        std:: cout<<" W = Prepare to die."<<endl;
        std:: cout<<" A = it's over, Shroud."<<endl;
        std:: cout<<" D = I'm here to fuck you up."<<endl;
        std:: cin>> a;
        
        if(a == 'a' || a == 'A'){
                    typewrite("\nYou: Hey, um Can I get a copy of that video when we're through here? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nCause it's over, Shroud. . . ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nnand it'd be nice to watch that back at a different angle.");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? : oh no. It's over, Shroud! ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? : All this buildup. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? turns around*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: Face to face with your father's killer and you come in here with that lame shit?");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou: Ugh. Where the fuck is shroud? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: He'll be here in a bit");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nOh, hey, after our conversation, I asked him about your dad. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nFun little tidbit, he was very well hydrated. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nIt turns out right after shroud shot him in the chest, your dad pissed his pants. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nBetcha didn't know that, huh? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSo, after that bullet tore through his insides, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nHe still had enough time to know how absolutely fucked he was, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nAnd just pissed himself like a little bitch. It was like, so much piss, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\ncommands mech*");
                        cout<<" "<<endl;
        }
        else if ( a == 'w' || a == 'W'){
                                typewrite("\nYou: Hey, um Can I get a copy of that video when we're through here?");
        this_thread::sleep_for(chrono::seconds(2));
                                typewrite("\nCause there are some people out there who're gonna want proof that you're dead.");
        this_thread::sleep_for(chrono::seconds(2));
                                typewrite("\n??? : oh no. Should I update my Wikipedia page? ");
        this_thread::sleep_for(chrono::seconds(2));
                                typewrite("\n??? : All this buildup. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? turns around*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: Face to face with your father's killer and you come in here with that lame shit?");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou: Ugh. Where the fuck is shroud? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: He'll be here in a bit");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nOh, hey, after our conversation, I asked him about your dad. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nFun little tidbit, he was very well hydrated. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nIt turns out right after shroud shot him in the chest, your dad pissed his pants. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nBetcha didn't know that, huh? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSo, after that bullet tore through his insides, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nHe still had enough time to know how absolutely fucked he was, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nAnd just pissed himself like a little bitch. It was like, so much piss, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\ncommands mech*");
                        cout<<" "<<endl;
        }
        else if ( a == 'd' || a == 'd'){
                    typewrite("\nYou: Hey, um Can I get a copy of that video when we're through here?");
        this_thread::sleep_for(chrono::seconds(2));
                    typewrite("\nCause I'm about to fuck you up and those videos do numbers. ");
        this_thread::sleep_for(chrono::seconds(2));
                    typewrite("\nMaybe we can go viral - - ");
        this_thread::sleep_for(chrono::seconds(2));
                    typewrite("\n???: Ohhh, Maybe we can go virallll. . .");
        this_thread::sleep_for(chrono::seconds(2));
                    typewrite("\n??? : All this buildup. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? turns around*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: Face to face with your father's killer and you come in here with that lame shit?");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou: Ugh. Where the fuck is shroud? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: He'll be here in a bit");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nOh, hey, after our conversation, I asked him about your dad. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nFun little tidbit, he was very well hydrated. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nIt turns out right after shroud shot him in the chest, your dad pissed his pants. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nBetcha didn't know that, huh? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSo, after that bullet tore through his insides, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nHe still had enough time to know how absolutely fucked he was, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nAnd just pissed himself like a little bitch. It was like, so much piss, ");
        this_thread::sleep_for(chrono::seconds(2));
                         typewrite("\ncommands mech*");
                         cout<<" "<<endl;

        }
        else{
                         typewrite("\nYou: Hey, um Can I get a copy of that video when we're through here? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nCause it's over, Shroud. . . ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nnand it'd be nice to watch that back at a different angle.");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? : oh no. It's over, Shroud! ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? : All this buildup. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n??? turns around*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: Face to face with your father's killer and you come in here with that lame shit?");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou: Ugh. Where the fuck is shroud? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSoothing voice: He'll be here in a bit");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nOh, hey, after our conversation, I asked him about your dad. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nFun little tidbit, he was very well hydrated. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nIt turns out right after shroud shot him in the chest, your dad pissed his pants. ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nBetcha didn't know that, huh? ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nSo, after that bullet tore through his insides, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nHe still had enough time to know how absolutely fucked he was, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nAnd just pissed himself like a little bitch. It was like, so much piss, ");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\ncommands mech*");
                        cout<<" "<<endl;
        }
      std::   cout <<" A = Punt"<<endl;
       std::  cout <<" D = Stomp"<<endl;
       std::  cin>> w;
        if (w == 'a' || w == 'A'){
                typewrite("Cause your dad was just wearing shorts so it just--");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Hey. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI get it. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLands mech* ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nKicks him epically, Sending him through the rooftop*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n ''Soothing voice gets injured pretty bad'' ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEnters mech and powers up menacingly*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n100+ aura ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Enters boss fight. . . ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: starting to think I didn't need to waste a perfectly good mattress to break your fall.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice: Perfectly good? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI assumed that cum-stained thing was already in the dumpster- -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice transforms* " );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCompletely naked* ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Cool dick.   So, you, uh, got some kinda clever supervillain name? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Toxic: you can call me toxic. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Bro, that works on so many levels for you. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: yeah, no shit, that's the point. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Fight begins. . . ");
        this_thread::sleep_for(chrono::seconds(2));
          std::       cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                 std::        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                 std::        cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(2));
                std::         cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou get ambushed and outnumbered*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n Mech gets stuck and heavily damaged*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Shroud shows up*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou activated shield*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n really yours anyway. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nShield energy depleting*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCalculating escape plan*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nsorry, pulse power to boosters, it won't work.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nThis is a limited time offer dude what's up? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou were so fucking talkative earlier? ");
                cout<<" "<<endl;
        }
        else if( w == 'd' || w == 'D'){
                typewrite("\nCause your dad was just wearing shorts so it just--");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Hey. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI get it. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nStomps him with mech menacingly*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n ''Soothing voice gets injured awfully bad''  ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEnters mech and powers up menacingly*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n “670+ aura”" );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEnters boss fight. . . ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: starting to think I didn't need to waste a perfectly good mattress to break your fall.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice: Perfectly good? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI assumed that cum-stained thing was already in the dumpster- -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice transforms* "  );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCompletely naked* ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Cool dick.   So, you, uh, got some kinda clever supervillain name? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Toxic: you can call me toxic. " );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Bro, that works on so many levels for you. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: yeah, no shit, that's the point. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Fight begins. . . "  );
        this_thread::sleep_for(chrono::seconds(2));
           std::      cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
              std::           cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                std::         cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(2));
              std::           cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou get ambushed and outnumbered*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nMech gets stuck and heavily damaged*" );
        this_thread::sleep_for(chrono::seconds(2));
               typewrite("\n Shroud shows up*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou activated shield*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't ");
        this_thread::sleep_for(chrono::seconds(1));
                typewrite("\n really yours anyway. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nShield energy depleting*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCalculating escape plan*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nsorry, pulse power to boosters, it won't work.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nThis is a limited time offer dude what's up? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou were so fucking talkative earlier? ");
                cout<<" "<<endl;
        }
        else{
           typewrite("Cause your dad was just wearing shorts so it just--");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Hey. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI get it. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLands mech* ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nKicks him epically, Sending him through the rooftop*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n ''Soothing voice gets injured pretty bad'' ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEnters mech and powers up menacingly*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n “100+ aura” ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Enters boss fight. . . ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: starting to think I didn't need to waste a perfectly good mattress to break your fall.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice: Perfectly good? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI assumed that cum-stained thing was already in the dumpster- -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Soothing voice transforms* " );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCompletely naked* ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Cool dick.   So, you, uh, got some kinda clever supervillain name? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Toxic: you can call me toxic. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: Bro, that works on so many levels for you. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: yeah, no shit, that's the point. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Fight begins. . . ");
        this_thread::sleep_for(chrono::seconds(2));
          std::       cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                 std::        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                 std::        cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(2));
                std::         cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nYou get ambushed and outnumbered*");
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\n Mech gets stuck and heavily damaged*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n Shroud shows up*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou activated shield*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\n really yours anyway. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nShield energy depleting*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nCalculating escape plan*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nsorry, pulse power to boosters, it won't work.");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nThis is a limited time offer dude what's up? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou were so fucking talkative earlier? ");
                cout<<" "<<endl;
        }
       std:: cout<<"W = Ignore him"<<endl;
       std::  cout<<"A = Bullshit"<<endl;
        std:: cout<<"D = you're bluffing."<<endl;
        std:: cin>>c;
        if(c == 'w' || c == 'W'){
                typewrite("\nI'm just a messenger here. . .");
        this_thread::sleep_for(chrono::seconds(2));

        }
        else if ( c == 'a' || c == 'A'){
                typewrite("\nYou: Bullshit "  );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: hey, mathblaster. i don't give a fuck, okay? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI'm just the messenger here. . . " );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nHe says you're not Calculating that shit stuck to your leg. . . Dumbass. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: fuck it"  );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLaunches boosters to max power*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Aye. Great. All going to plan. Now get outta there, babe. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLaunches it*" );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEscapes. . . ");
        this_thread::sleep_for(chrono::seconds(2));

        }
        else if(c == 'd' || c == 'D') {
                        cout<<"You: you're bluffing"  <<endl;
        this_thread::sleep_for(chrono::seconds(2));
                        typewrite("\nToxic: hey, mathblaster. i don't give a fuck, okay? ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nI'm just the messenger here. . . " );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nHe says you're not Calculating that shit stuck to your leg. . . Dumbass. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nYou: fuck it"  );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLaunches boosters to max power*");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nToxic: Aye. Great. All going to plan. Now get outta there, babe. ");
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nLaunches it*" );
        this_thread::sleep_for(chrono::seconds(2));
                typewrite("\nEscapes. . . ");
        this_thread::sleep_for(chrono::seconds(5));

        }
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<"Warning! "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Warning! "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"System: foreign object detected"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Explodes* "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        typewrite("\n Welcome to Dispatch");

}

int main()
{
    warehouse();

    return 0;
}

