#include <iostream>
#include <thread>//function for pause
#include <chrono>// declaration of seconds and milliseconds
using namespace std;
void warehouse(){
        cout<<"Suiting upp. . ."<<endl;
        this_thread::sleep_for(chrono::seconds(3));
        cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"Entering mech. . ."<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"Invading warehouse . . "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"Beat up some hooligans*"<<endl;
        this_thread::sleep_for(chrono::seconds(2));
                cout<<"Entering Boss room. . ."<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(1));
                cout<<"Sees cctv footages*"<<endl;
        this_thread::sleep_for(chrono::seconds(2));
        char a, w, c;
        cout<<" W = Prepare to die."<<endl;
        cout<<" A = it's over, Shroud."<<endl;
        cout<<" D = I'm here to fuck you up."<<endl;
        cin>> a;
        
        if(a == 'a' || a == 'A'){
                    cout<<"You: Hey, um Can I get a copy of that video when we're through here? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Cause it's over, Shroud. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"and it'd be nice to watch that back at a different angle."<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? : oh no. It's over, Shroud! "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Soothing voice: He'll be here in a bit"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Oh, hey, after our conversation, I asked him about your dad. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Fun little tidbit, he was very well hydrated. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"It turns out right after shroud shot him in the chest, your dad pissed his pants. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"Betcha didn't know that, huh? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"So, after that bullet tore through his insides, "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He still had enough time to know how absolutely fucked he was, "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"And just pissed himself like a little bitch. It was like, so much piss, "<<endl;
                                                                               this_thread::sleep_for(chrono::seconds(6));
                                                cout<<"commands mech*"<<endl;
        }
        else if ( a == 'w' || a == 'W'){
                                cout<<"You: Hey, um Can I get a copy of that video when we're through here?"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"Cause there are some people out there who're gonna want proof that you're dead."<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"??? : oh no. Should I update my Wikipedia page? "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Soothing voice: He'll be here in a bit"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Oh, hey, after our conversation, I asked him about your dad. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Fun little tidbit, he was very well hydrated. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"It turns out right after shroud shot him in the chest, your dad pissed his pants. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"Betcha didn't know that, huh? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"So, after that bullet tore through his insides, "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He still had enough time to know how absolutely fucked he was, "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"And just pissed himself like a little bitch. It was like, so much piss, "<<endl;
                                                                               this_thread::sleep_for(chrono::seconds(6));
                                                cout<<"commands mech*"<<endl;
        }
        else if ( a == 'd' || a == 'd'){
            cout<<"You: Hey, um Can I get a copy of that video when we're through here?"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                    cout<<"Cause I'm about to fuck you up and those videos do numbers. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                    cout<<"Maybe we can go viral - - "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                    cout<<"???: Ohhh, Maybe we can go virallll. . ."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Soothing voice: He'll be here in a bit"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Oh, hey, after our conversation, I asked him about your dad. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Fun little tidbit, he was very well hydrated. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"It turns out right after shroud shot him in the chest, your dad pissed his pants. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"Betcha didn't know that, huh? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"So, after that bullet tore through his insides, "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He still had enough time to know how absolutely fucked he was, "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"And just pissed himself like a little bitch. It was like, so much piss, "<<endl;
                                                       this_thread::sleep_for(chrono::seconds(6));
                                                cout<<"commands mech*"<<endl;

        }
        else{
                        cout<<"You: Hey, um Can I get a copy of that video when we're through here? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Cause it's over, Shroud. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"and it'd be nice to watch that back at a different angle."<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? : oh no. It's over, Shroud! "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"??? : All this buildup. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"??? turns around*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Soothing voice: Face to face with your father's killer and you come in here with that lame shit?"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Ugh. Where the fuck is shroud? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Soothing voice: He'll be here in a bit"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Oh, hey, after our conversation, I asked him about your dad. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Fun little tidbit, he was very well hydrated. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"It turns out right after shroud shot him in the chest, your dad pissed his pants. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"Betcha didn't know that, huh? "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"So, after that bullet tore through his insides, "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He still had enough time to know how absolutely fucked he was, "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"commands mech*"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
        }
        cout <<" A = Punt"<<endl;
        cout <<" D = Stomp"<<endl;
        cin>> w;
        if (w == 'a' || w == 'A'){
                cout<<"Cause your dad was just wearing shorts so it just--"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Hey. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I get it. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"Lands mech* "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Kicks him epically, Sending him through the rooftop*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" ''Soothing voice gets injured pretty bad'' "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Enters mech and powers up menacingly*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" “100+ aura” "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" Enters boss fight. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
        cout<<"You: starting to think I didn't need to waste a perfectly good mattress to break your fall."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice: Perfectly good? "  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I assumed that cum-stained thing was already in the dumpster- -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice transforms* "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"Completely naked* "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You: Cool dick.   So, you, uh, got some kinda clever supervillain name? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Toxic: you can call me toxic. "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Bro, that works on so many levels for you. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"Toxic: yeah, no shit, that's the point. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Fight begins. . . "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You get ambushed and outnumbered*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<" Mech gets stuck and heavily damaged*"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<" Shroud shows up*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                             cout<<"You activated shield*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<" really yours anyway. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"Shield energy depleting*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Calculating escape plan*"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Toxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Sorry, pulse power to boosters, it won't work."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"This is a limited time offer dude what's up? "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You were so fucking talkative earlier? "<<endl;
        }
        else if( w == 'd' || w == 'D'){
                cout<<"Cause your dad was just wearing shorts so it just--"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Hey. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I get it. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Stomps him with mech menacingly*"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<" ''Soothing voice gets injured awfully bad''  "  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"Enters mech and powers up menacingly*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" “670+ aura”"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"Enters boss fight. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
        cout<<"You: starting to think I didn't need to waste a perfectly good mattress to break your fall."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice: Perfectly good? "  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I assumed that cum-stained thing was already in the dumpster- -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice transforms* "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"Completely naked* "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You: Cool dick.   So, you, uh, got some kinda clever supervillain name? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Toxic: you can call me toxic. "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Bro, that works on so many levels for you. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"Toxic: yeah, no shit, that's the point. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Fight begins. . . "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You get ambushed and outnumbered*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<" Mech gets stuck and heavily damaged*"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<" Shroud shows up*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                             cout<<"You activated shield*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<" really yours anyway. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"Shield energy depleting*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Calculating escape plan*"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Toxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Sorry, pulse power to boosters, it won't work."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"This is a limited time offer dude what's up? "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You were so fucking talkative earlier? "<<endl;
        }
        else{
             cout<<"Cause your dad was just wearing shorts so it just--"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Hey. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I get it. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"Lands mech* "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Kicks him epically, Sending him through the rooftop*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" ''Soothing voice gets injured pretty bad'' "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Enters mech and powers up menacingly*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" “100+ aura” "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<" Enters boss fight. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
        cout<<"You: starting to think I didn't need to waste a perfectly good mattress to break your fall."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice: Perfectly good? "  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<"I assumed that cum-stained thing was already in the dumpster- -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: Can we just skip to the part where you reveal your bullshit superpower so we can fight for real? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Soothing voice transforms* "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"Completely naked* "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You: Cool dick.   So, you, uh, got some kinda clever supervillain name? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Toxic: you can call me toxic. "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<"You: Bro, that works on so many levels for you. "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"Toxic: yeah, no shit, that's the point. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<" Fight begins. . . "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"."<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"You get ambushed and outnumbered*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<" Mech gets stuck and heavily damaged*"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                cout<<" Shroud shows up*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                             cout<<"You activated shield*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: Good news, buddy. Shroud says he just wants the Astral Pulse. Which, we all know, isn't "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                cout<<" really yours anyway. "<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"Shield energy depleting*"<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Calculating escape plan*"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Toxic: Oh, hey. Boss man says if you're planning on diverting puss pow- - -"<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Sorry, pulse power to boosters, it won't work."<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"This is a limited time offer dude what's up? "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You were so fucking talkative earlier? "<<endl;
        }
        cout<<"W = Ignore him"<<endl;
        cout<<"A = Bullshit"<<endl;
        cout<<"D = you're bluffing.";
        cin>>c;
        if(c == 'w' || c == 'W'){
                         cout<<"I'm just a messenger here. . ."<<endl;
        this_thread::sleep_for(chrono::seconds(6));

        }
        else if ( c == 'a' || c == 'A'){
                        cout<<"You: Bullshit "  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: hey, mathblaster. i don't give a fuck, okay? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"I'm just the messenger here. . . "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He says you're not Calculating that shit stuck to your leg. . . Dumbass. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"You: fuck it"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Launches boosters to max power*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: Aye. Great. All going to plan. Now get outta there, babe. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"Launches it*"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Escapes. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(5));

        }
        else if(c == 'd' || c == 'D') {
                        cout<<"You: you're bluffing"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Toxic: hey, mathblaster. i don't give a fuck, okay? "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                      cout<<"I'm just the messenger here. . . "  <<endl;
        this_thread::sleep_for(chrono::seconds(6));
                        cout<<"He says you're not Calculating that shit stuck to your leg. . . Dumbass. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"You: fuck it"  <<endl;
        this_thread::sleep_for(chrono::seconds(5));
                        cout<<"Launches boosters to max power*"<<endl;
        this_thread::sleep_for(chrono::seconds(5));
                                cout<<"Toxic: Aye. Great. All going to plan. Now get outta there, babe. "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<"Launches it*"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Escapes. . . "<<endl;
        this_thread::sleep_for(chrono::seconds(5));

        }
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<"Warning! "  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Warning! "<<endl;
        this_thread::sleep_for(chrono::seconds(4));
                                cout<<"System: foreign object detected"  <<endl;
        this_thread::sleep_for(chrono::seconds(4));
                        cout<<"Explodes* "<<endl;
        this_thread::sleep_for(chrono::seconds(6));
                                cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "  <<endl;
        this_thread::sleep_for(chrono::seconds(3));
                        cout<<". "<<endl;
                        

}

int main()
{
    void warehouse();

    return 0;
}
